tasks:
  - build:
      name: Bazel Build
      bazel:
        flags:
          - --jobs=HOST_CPUS
  
  - test:
      name: Bazel Test
      bazel:
        flags:
          - --test_output=errors
          - --jobs=HOST_CPUS