# hello_world/BUILD

load("@rules_python//python:defs.bzl", "py_binary")

# Este target executará a função say_hello
py_binary(
    name = "hello",
    srcs = ["hello.py"],
    main = "hello.py",
)

# Este target executará a função say_goodbye
py_binary(
    name = "goodbye",
    srcs = ["hello.py"],
    main = "hello.py",
)