# .github/workflows/main.yml
name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # This job simply calls the reusable workflow.
  call-aspect-workflows: # Renamed job for clarity
    name: Run Aspect Workflows
    # Uses the file path for the reusable workflow.
    uses: ./.github/workflows/.aspect_workflows_reusable.yml