name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  aspect-workflows:
    name: Aspect Workflows
    uses: ./.github/workflows/.aspect_workflows_reusable.yml
    with:
        queue: aspect-small