name: CI
on:
  pull_request:
    branches:
      - "*" # Executa em qualquer Pull Request
  push:
    branches:
      - "main" # Executa quando há push para a branch main

concurrency:
  # Garante que apenas uma execução por PR/branch esteja ativa por vez.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  aspect-workflows:
    name: Aspect Workflows
    # Chama o workflow reutilizável que contém a lógica de Build e Teste.
    uses: ./.github/workflows/.aspect_workflows_reusable.yml
    
    # ATENÇÃO: Esta é a correção crítica. 
    # 'aspect-default' corresponde à 'queue' do grupo 'default' no seu Terraform, 
    # que é o grupo designado para tarefas de build e teste (Bazel).
    with:
        queue: aspect-default