# .github/workflows/.aspect_workflows_reusable.yml
name: Aspect Workflows - Reusable CI Logic
on:
  workflow_call:
    # This allows the workflow to be called from other workflows (reusable workflow)

jobs:
  aspect-workflows:
    name: Aspect Build and Test

    runs-on: [self-hosted, aspect-workflows, aspect-default]

    env:
      ASPECT_WORKFLOWS_BIN_DIR: /etc/aspect/workflows/bin

    steps:
      - name: Workflows environment
        # Runs the configuration script installed on the Aspect Workflows runner
        run: ${ASPECT_WORKFLOWS_BIN_DIR}/configure_workflows_env
        
      - uses: actions/checkout@v4
        
      - name: Agent health check
        run: ${ASPECT_WORKFLOWS_BIN_DIR}/agent_health_check

      - name: Run Bazel Build and Test
        # Uses the Aspect Workflows GitHub Action to execute the build/test logic
        uses: aspect-build/workflows-action@v5 # Replace 'v5' with the actual version
        with:
          task: ci # Assuming the default 'ci' task (build and test)