name: Aspect Workflows CI (Build and Test)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  aspect-workflows-ci:
    name: Build and Test
    runs-on: [self-hosted, aspect-workflows, aspect-default]

    steps:
      - name: Configure Workflows Environment
        run: /etc/aspect/workflows/bin/configure_workflows_env

      - uses: actions/checkout@v4

      - name: Agent Health Check
        # **Mude para rodar dentro da pasta do Bazel workspace**
        run: |
          cd workspace
          /etc/aspect/workflows/bin/agent_health_check

      - name: Run Aspect Workflows CI
        uses: aspect-build/workflows-action@5.14.16
        with:
          task: ci
          # Aponta para a subpasta 'workspace' como raiz Bazel
          workspace: 'workspace'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
